package speakingclub.app.model.enums;

public enum CourseDirection {
    ALL,
    BLOGGERS,
    CEO_AND_MANAGERS,
    CONSULTANTS_AND_ADVISORS,
    ENTREPRENEURS_AND_STARTUP_FOUNDERS,
    FOR_EVERYDAY_LIFE,
    HEALTHCARE_PROFESSIONALS,
    IT_SPECIALISTS,
    LIFE_COACHES,
    MARKETING_PROFESSIONALS_AND_PR_SPECIALISTS
}
